### ISSUE TITLE
Gitignore removes .lib files from FMOD library

### ISSUE THREAD

**Issue by DylanDeWaele** [samynk/DeepDarkCave#1]
When trying the build the project, I get an error saying it is unable to open the fmodL_vc.lib. Could it be that the .lib files of FMOD still need to be included into the source, regardless of the .gitignore? Or is there another way to solve this issue?

**Comment by samynk** [comment]
ah right, will add the .lib files of fmod as special case.

**Comment by samynk** [comment]
fixed
